### ISSUE TITLE
Can't Send APDU: Error executing command: error: operation failed: Unknown status 0x87430003

### ISSUE THREAD

**Issue by bam80** [estkme-group/lpac#114]
The modem is Fibocom L860GL-16, using [lpac-libmbim-wrapper](https://github.com/stich86/lpac-libmbim-wrapper/issues/8).

Logic Channel seems successfully open but then `Send APDU:` part fails, I tried different commands:
```
$ DEBUG=1 ./wrapper.py chip info
recv={"type":"apdu","payload":{"func":"connect","param":null}}
INFO: Connect
send={"type": "apdu", "payload": {"ecode": 0}}
recv={"type":"apdu","payload":{"func":"logic_channel_open","param":"a0000005591010ffffffff8900000100"}}
INFO: Open channel with AID a0000005591010ffffffff8900000100
send={"type": "apdu", "payload": {"ecode": 1}}
recv={"type":"apdu","payload":{"func":"transmit","param":"81e2910006bf3e035c015a"}}
Send APDU: 81e2910006bf3e035c015a
Error executing command: error: operation failed: Unknown status 0x87430003

Traceback (most recent call last):
  File "/var/home/bam/lpac/output/./wrapper.py", line 159, in <module>
    main()
  File "/var/home/bam/lpac/output/./wrapper.py", line 144, in main
    payload = handle_type_apdu(req["payload"]["func"], req["payload"]["param"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/bam/lpac/output/./wrapper.py", line 92, in handle_type_apdu
    data = send_apdu(param)
           ^^^^^^^^^^^^^^^^
  File "/var/home/bam/lpac/output/./wrapper.py", line 35, in send_apdu
    output_cmd = run_mbimcli(f'--ms-set-uicc-apdu="channel={CHANNEL_ID},command={apdu}"').split('\n')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

⬢[bam@toolbox output]$ mbimcli --device=/dev/cdc-wdm0 --intel-modem-reboot
[/dev/cdc-wdm0] Successfully requested modem to reboot for firmware update

⬢[bam@toolbox output]$ DEBUG=1 ./wrapper.py profile list
recv={"type":"apdu","payload":{"func":"connect","param":null}}
INFO: Connect
send={"type": "apdu", "payload": {"ecode": 0}}
recv={"type":"apdu","payload":{"func":"logic_channel_open","param":"a0000005591010ffffffff8900000100"}}
INFO: Open channel with AID a0000005591010ffffffff8900000100
send={"type": "apdu", "payload": {"ecode": 1}}
recv={"type":"apdu","payload":{"func":"transmit","param":"81e2910003bf2d00"}}
Send APDU: 81e2910003bf2d00
Error executing command: error: operation failed: Unknown status 0x87430003

Traceback (most recent call last):
  File "/var/home/bam/lpac/output/./wrapper.py", line 159, in <module>
    main()
  File "/var/home/bam/lpac/output/./wrapper.py", line 144, in main
    payload = handle_type_apdu(req["payload"]["func"], req["payload"]["param"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/bam/lpac/output/./wrapper.py", line 92, in handle_type_apdu
    data = send_apdu(param)
           ^^^^^^^^^^^^^^^^
  File "/var/home/bam/lpac/output/./wrapper.py", line 35, in send_apdu
    output_cmd = run_mbimcli(f'--ms-set-uicc-apdu="channel={CHANNEL_ID},command={apdu}"').split('\n')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
```
Also, if I open the Channel manually and then try to immediately close, it fails:
```
 $ mbimcli -d /dev/cdc-wdm0 --ms-set-uicc-open-channel="application-id=a0000005591010ffffffff8900000100" 
Succesfully retrieved open channel info:
	  status: 144
	 channel: 1
	response: (null)

$ mbimcli -d /dev/cdc-wdm0 --ms-set-uicc-close-channel="channel=1"
error: operation failed: Unknown status 0x87430003
```
What could I else try to diagnose it?

**Comment by septs** [comment]
i don't see how this issue is related to lpac

**Comment by septs** [comment]
recommended, contact fibocom FAE engineer for technical support.

**Comment by bam80** [comment]
> i don't see how this issue is related to lpac

The problem is, the modem's eSIM works with the same MBIM mode in Windows:
https://github.com/stich86/lpac-libmbim-wrapper/issues/8#issuecomment-2159297536

So it seems like the problem can actually be on `lpac` side, but I don't know the details so any help to debug it further is welcomed.

**Comment by septs** [comment]
recommended, you contact fibocom FAE engineer.
this a mobile module cannot close the channel, i think it is a firmware bug.
